apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002   #it does not have public access only frontend needs to connect it via cluster IP
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: uday27/orders-microservice:2026.01.05
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: microservices-config
            # - secretRef:
            #     name: microservices-secrets 
          readinessProbe:
            httpGet:
              path: /api/orders/health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/orders/health
              port: 8002  
            initialDelaySeconds: 10
            periodSeconds: 15
      # imagePullSecrets:
      #   - name: regcred
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config  
  labels:
    app: orders
data:
  # Add your configuration key-value pairs here
  DATABASE_URL: postgresql://user:password@postgres-service:5432/orders_db
  AUTH_SERVICE_URL: http://auth-service:8000
  INVENTORY_SERVICE_URL: http://inventory-service:8001  
  PAYMENT_SERVICE_URL: http://payment-service:8003
  # Add other necessary environment variables here
  