apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003   #it does not have public access only frontend needs to connect it via cluster IP
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: uday27/payment-microservice:2026.01.05
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: microservices-config
            # - secretRef:
            #     name: microservices-secrets 
          readinessProbe:
            httpGet:
              path: /api/payments/health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/payments/health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 15
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config  
  namespace: default
  labels:
    app: payment
data:
  PAYMENT_DB_HOST: payment-db
  PAYMENT_DB_PORT: "5432"
  PAYMENT_DB_NAME: payments_db
  PAYMENT_DB_USER: postgres
  PAYMENT_DB_PASSWORD: your_password_here
  PAYMENT_SERVICE_PORT: "8003"
  AUTH_SERVICE_HOST: auth-service
  AUTH_SERVICE_PORT: "8000"
  INVENTORY_SERVICE_HOST: inventory-service
  INVENTORY_SERVICE_PORT: "8001"
  ORDERS_SERVICE_HOST: orders-service
  ORDERS_SERVICE_PORT: "8002" 
  PAYMENT_SERVICE_HOST: payment-service
  PAYMENT_SERVICE_PORT: "8003"
  # Add your configuration key-value pairs here
  DATABASE_URL: postgresql://postgres:your_password_here@payment-db:5432/payments_db
  AUTH_SERVICE_URL: http://auth-service:8000
  INVENTORY_SERVICE_URL: http://inventory-service:8001
  ORDERS_SERVICE_URL: http://orders-service:8002
  PAYMENT_SERVICE_URL: http://payment-service:8003
  # For example: