apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
  labels:
    app: payment-db 
spec:
  selector:
    app: payment-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-deployment
  labels:
    app: payment-db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:15      
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: microservices-config
                  key: PAYMENT_DB_NAME
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config  
  namespace: default
data:
  POSTGRES_USER: postgres
  PAYMENT_DB_NAME: payments_db
  